### ISSUE TITLE
Find a better name

### ISSUE THREAD

**Issue by mhugo** [Oslandia/QGeoloGIS#12]
Proposals:
- QGeologist

**Comment by troopa81** [comment]
Why not just **QGeology** ?

**Comment by delhomer** [comment]
As a compromise: **QGeologis**

**Comment by mhugo** [comment]
Yes GeoloGIS was my primary idea, but it is already taken ...

**Comment by sylvainbeo** [comment]
Qarrot ?  :)

**Comment by haubourg** [comment]
mm, well log viewer, reader and plotter are the names used elsewhere: 
http://www.geoloil.com/logLAS.php

or well plotter here: https://hydrooffice.org/Tool/WellPlotter

https://resinsight.org/docs/welllogsandplots/

Why is the current name not satisying? 

We could shorten it removing the QGIS prefix, and add `plot`. **QWellLogPlotter** ?

**Comment by mhugo** [comment]
There is a company named geologis in UK, but I think it does not harm to have a distinct QGIS plugin called QGeoloGIS. I will rename files and class names this way if there are no objections

**Comment by mhugo** [comment]
Renamed to QGeoloGIS
