### ISSUE TITLE
Ergonomic refactor

### ISSUE THREAD

**Issue by troopa81** [Oslandia/QGeoloGIS#14]
I'm planning to make some major modifications on QGeoloGIS to improve usability: 
- Remove QGIS 2 compatibility (QGIS 2 is no longer supported) and fix style file management for QGIS 3
- Make the QGeoloGIS window unique and dockable. Its content will be updated according to the current identified feature
- Load the QGeoloGIS configuration from project file (and later be able to edit and save this configuration)
- Replace the "data to add" list with a checkboxes list that manage the visibility for a given data (it won't be possible to add the same data several times anymore)
- Save column order in project file
- Use layerid instead of uri+provider when configuring plot. Then, it will be possible to use virtual field in plot.

I'm planning to propose a PR in the days to come for these modifications.

Just for the record, I think it will also be interesting to have in QGeoloGIS:
- Connect to selection to display and compare plot from different feature
- Edit configuration from IHM

@mhugo @vmora

**Comment by mhugo** [comment]
Now merged
