### ISSUE TITLE
Allow for simpler categorized column representation

### ISSUE THREAD

**Issue by vmora** [Oslandia/QGeoloGIS#36]
For the moment the stratigraphic column type needs two columns to work, making one of them optional would be a nice feature.

**Comment by mhugo** [comment]
@vmora They should already be optional, i.e. you can have null values for them.

If you only one of them (either "rock_code" or "formation_code"), you should use a simplified style.

Do you need something more ? Do not label the formation and span the first column on the whole width ?

**Comment by vmora** [comment]
@mhugo you must choose in the interface a column that does not exist in my case, I don't feel like adding a fake column with null values.

**Comment by mhugo** [comment]
Fixed
