### ISSUE TITLE
Include time series

### ISSUE THREAD

**Issue by mhugo** [Oslandia/QGeoloGIS#8]
The PlotItem class has been designed to display both vertical "XZ" data and "XY" horizontal data.
We usually plot log data vertically and time series horizontally.
And thinking about it, some could want to represent log data horizontally (why not ?)

The project is called "qgis_well_log", should it be renamed so that we understand it covers both types of data ?

@troopa81 @vmora

**Comment by mhugo** [comment]
Related design question: should we add a TimeSeriesView in addition to WellLogView ?
Or make WellLogView generic enough (and with a better name) so that it can be "rotated" ?

It would vote for the second if does not make the code too complex, because operations on timeseries and well logs would be very close (superimpose another series, "merge" with another, change styling, etc.)

**Comment by troopa81** [comment]
> The PlotItem class has been designed to display both vertical "XZ" data and "XY" horizontal data.

From what I remember you can choose any fields from your data to be the X and Y axis of your graph, and you can choose the layout (horizontal or vertical). So anything is possible, no?

> It would vote for the second if does not make the code too complex, because operations on timeseries and well logs would be very close

I would go also for the second one.
Key question here is : Do we want a library to display well log only or do we want a library to display any chart (including timeseries).

**Comment by mhugo** [comment]
@troopa81 @vmora @delhomer I've added support for timeseries [see here](https://github.com/Oslandia/qgis_well_log/blob/master/well_log/timeseries_view.py). This is very similar to the "well logs" view and there should still be room for factorization, but this is a start.

![Capture d’écran de 2019-04-05 10-38-38](https://user-images.githubusercontent.com/1618556/55615188-078afd80-578f-11e9-82b8-04a30ac117c6.png)

That pushes us to find a better name :) Maybe something more focused on (hydro)geology ? QGeologist ?

**Comment by troopa81** [comment]
Nice work @mhugo ! 

QGeologist seems fine to me

**Comment by mhugo** [comment]
New ticket for the name question : https://github.com/Oslandia/qgis_well_log/issues/12
